# Site settings
title: WOSP Personas
email: webmaster@tepapa.govt.nz
description: Te Papa's personas for the website and online services project (WOSP)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
